version: '3.8'

networks:
  app_network:

volumes:
  mysql_volumes:

services:

  # =========================== nginx service ============================
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./service-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_app
      - db
    networks:
      - app_network

  # ============================= Mysql =====================================
  db:
    container_name: mysql_container
    image: mysql:8.0.30
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: chhay
      MYSQL_PASSWORD: chhay
      MYSQL_ROOT_PASSWORD: chhay
    ports:
      - "3307:3306"
    volumes:
      - mysql_volumes:/var/lib/mysql/
    networks:
      - app_network

  # ============================= phpmyadmin =============================
  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: chhay
    ports:
      - "3400:80"
    depends_on:
      - db
    networks:
      - app_network


  # ============================= laravel app ==============================
  laravel_app:
    build: .
    container_name: laravel_app_container
    tty: true
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: chhay
      DB_PASSWORD: chhay
      DB_ROOT_PASSWORD: chhay
    ports:
      - "9000:8000"
    volumes:
      - ./:/var/www/html
      # - ./service-config/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    networks:
      - app_network


# NOTE: volumes in web server and volumes in application must be the same directory 
# so everything in application container is also has in web server container so web server can serve the content
# like in nginx
# volumes:
#   - ./:/var/www/html
# in laravel_app 
# volumes:
#   - ./:/var/www/html